// Code generated by dagger-compiler.  Do not edit.
package com.lunchlunch.webcomm.login;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class LoginHelperProvider$$ModuleAdapter extends ModuleAdapter<LoginHelperProvider> {
  private static final String[] INJECTS = { "members/com.lunchlunch.view.login.Login", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public LoginHelperProvider$$ModuleAdapter() {
    super(com.lunchlunch.webcomm.login.LoginHelperProvider.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, false /*complete*/, false /*library*/);
  }

  @Override
  public LoginHelperProvider newModule() {
    return new com.lunchlunch.webcomm.login.LoginHelperProvider();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, LoginHelperProvider module) {
    bindings.contributeProvidesBinding("com.lunchlunch.webcomm.login.LoginHelperInterface", new ProvideLoginHelperProvidesAdapter(module));
  }

  /**
   * A {@code Binding<com.lunchlunch.webcomm.login.LoginHelperInterface>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<com.lunchlunch.webcomm.login.LoginHelperInterface>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideLoginHelperProvidesAdapter extends ProvidesBinding<LoginHelperInterface>
      implements Provider<LoginHelperInterface> {
    private final LoginHelperProvider module;

    public ProvideLoginHelperProvidesAdapter(LoginHelperProvider module) {
      super("com.lunchlunch.webcomm.login.LoginHelperInterface", IS_SINGLETON, "com.lunchlunch.webcomm.login.LoginHelperProvider", "provideLoginHelper");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<com.lunchlunch.webcomm.login.LoginHelperInterface>}.
     */
    @Override
    public LoginHelperInterface get() {
      return module.provideLoginHelper();
    }
  }
}
